driver:
  name: vagrant
  provider: vmware_fusion
  customize:
    vhv.enable: "TRUE"
    numvcpus: 2
    memsize: 2048

provisioner:
  name: chef_zero
  require_chef_omnibus: 13

verifier:
  name: inspec

platforms:
- name: macos-10.12
  attributes:
    bento:
      vmware_key: <%= ENV["VMWARE_FUSION_KEY"] %>
- name: ubuntu-16.04
  attributes:
    bento:
      vmware_key: <%= ENV["VMWARE_WORKSTATION_KEY"] %>

suites:
  - name: default
    run_list: bento
    excludes: ["macos-10.12"]
  - name: build-1604
    run_list:
      - bento_test
    excludes: ["macos-10.12"]
